on:
  push:
    branches: 
      - master
    paths-ignore:
      - '.github/'
       
  pull_request:
    branches:
      - master
    paths-ignore:
        - '.github/'

jobs:
  build:
    name: Merge into delpoying branch
    env:
      my_secret: ${{ secrets.TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - uses: subosito/flutter-action@v1
      #   with:
      #     channel: stable
      # - run: flutter config --enable-web
      - run: echo "Hello"
      # - run: flutter pub get
      # - run: flutter build web
      # - run: |
      #     git checkout firebase_delpoy
      #     git merge origin/master

      