on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Merge into delpoying branch
    env:
      my_secret: ${{ secrets.TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          git checkout -b firebase_delpoy
          git merge master          
          git push origin firebase_delpoy

      