on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Merge into delpoying branch
    env:
      my_secret: ${{ secrets.TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          git init
          git config --global user.email sharathnaik89@gmail.com
          git config --global user.name sharath-b-naik
          git config --global init.defaultBranch master
          git remote add origin https://${{ secrets.TOKEN }}@github.com/sharath-b-naik/hosting.git
          git checkout -b firebase_deploy
          git merge master          
          git push origin firebase_deploy -f

      